function _precompile_()
    #    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(searchsortedfirst, (Array{Int64,1}, Base.StepRange{Int64,Int64}, Int64, Int64))
    precompile(searchsortedfirst, (Array{Int64,1}, Int64, Int64, Int64))
    precompile(tail, (RLEVector{Int64,Int64}, Int64))
    precompile(searchsortedfirst, (Array{Int64,1}, Array{Int64,1}, Int64, Int64))
    precompile(length, (RLEVector{Int64,Int64},))
    precompile(numruns, (Array{Int64,1}, Array{Int64,1}))
    precompile(getindex, (RLEVector{Int64,Int64}, Base.UnitRange{Int64}))
    precompile(ind2run, (RLEVector{Int64,Int64}, Base.UnitRange{Int64}))
    precompile(numruns, (Array{Int64,1},))
    precompile(ree, (Array{Int64,1}, Array{Int64,1}, Int64))
    precompile(ind2runcontext, (RLEVector{Int64,Int64}, Int64))
    precompile(getindex, (RLEVector{Int64,Int64}, Base.StepRange{Int64,Int64}))
    precompile(inverse_ree, (Array{Int64,1}, Array{Int64,1}))
    precompile(ree, (Array{Int64,1},))
    precompile(ind2runcontext, (RLEVector{Int64,Int64}, Base.UnitRange{Int64}))
    precompile(setindex!, (RLEVector{Int64,Int64}, Int64, Int64))
    precompile(setindex!, (RLEVector{Int64,Int64}, Int64, Base.UnitRange{Int64}))
    precompile(Type, (Type{RLEVector}, Array{Int64,1}, Array{Int64,1}))
    precompile(setindex!, (RLEVector{Int64,Int64}, Array{Int64,1}, Array{Bool,1}))
    precompile(ind2run, (RLEVector{Int64,Int64}, Array{Int64,1}))
    precompile(ind2run, (RLEVector{Int64,Int64}, Int64))
    precompile(getindex, (RLEVector{Int64,Int64}, Array{Int64,1}))
    precompile(ind2run, (RLEVector{Int64,Int64}, Base.StepRange{Int64,Int64}))
    precompile(Type, (Type{RLEVector}, Array{Int64,1}))
end
